services:
  - type: web
    name: reportes-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        fromDatabase:
          name: reportes-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: reportes-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://reportes-backend.onrender.com

databases:
  - name: reportes-db
    databaseName: reportes_sistema
    user: reportes_user